import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = resolve(scriptDirectory, "../..");
const schemaPath = resolve(
  repositoryRoot,
  "protocol/schema/scope-protocol.json",
);
const schema = JSON.parse(await readFile(schemaPath, "utf8"));

const primitiveRust = {
  bool: "bool",
  f64: "f64",
  string: "String",
  u32: "u32",
  u64: "u64",
};

const primitiveTypeScript = {
  bool: "boolean",
  f64: "number",
  string: "string",
  u32: "number",
  u64: "number",
};

function convertType(type, primitives, arrayFormat, optionalFormat) {
  if (type.endsWith("[]")) {
    return arrayFormat(
      convertType(type.slice(0, -2), primitives, arrayFormat, optionalFormat),
    );
  }
  if (type.endsWith("?")) {
    return optionalFormat(
      convertType(type.slice(0, -1), primitives, arrayFormat, optionalFormat),
    );
  }
  return primitives[type] ?? type;
}

const rust = [
  "// @generated by protocol/scripts/generate-types.mjs. Do not edit.",
  "",
  "use serde::{Deserialize, Serialize};",
  "",
  `pub const PROTOCOL_VERSION: u32 = ${schema.protocol_version};`,
  "",
];

const typeScript = [
  "// @generated by protocol/scripts/generate-types.mjs. Do not edit.",
  "",
  `export const PROTOCOL_VERSION = ${schema.protocol_version} as const;`,
  "",
];

for (const [name, definition] of Object.entries(schema.types)) {
  if (definition.kind !== "object") {
    throw new Error(`Unsupported schema kind: ${definition.kind}`);
  }

  rust.push("#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]");
  rust.push(`pub struct ${name} {`);
  typeScript.push(`export interface ${name} {`);
  for (const [field, type] of Object.entries(definition.fields)) {
    if (type.endsWith("?")) {
      rust.push("    #[serde(default)]");
    }
    rust.push(
      `    pub ${field}: ${convertType(
        type,
        primitiveRust,
        (value) => `Vec<${value}>`,
        (value) => `Option<${value}>`,
      )},`,
    );
    typeScript.push(
      `  ${field}: ${convertType(
        type,
        primitiveTypeScript,
        (value) => `${value}[]`,
        (value) => `${value} | null`,
      )};`,
    );
  }
  rust.push("}", "");
  typeScript.push("}", "");
}

await writeFile(
  resolve(repositoryRoot, "protocol/src/generated.rs"),
  `${rust.join("\n").trimEnd()}\n`,
);
await writeFile(
  resolve(repositoryRoot, "frontend/src/generated/protocol.ts"),
  `${typeScript.join("\n").trimEnd()}\n`,
);
