// @generated by protocol/scripts/generate-types.mjs. Do not edit.

use serde::{Deserialize, Serialize};

pub const SESSION_SCHEMA_VERSION: u32 = 13;

mod u64_string {
    use serde::{Deserialize, Deserializer, Serializer, de::Error};

    #[allow(clippy::trivially_copy_pass_by_ref)]
    pub fn serialize<S>(value: &u64, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(&value.to_string())
    }

    pub fn deserialize<'de, D>(deserializer: D) -> Result<u64, D::Error>
    where
        D: Deserializer<'de>,
    {
        String::deserialize(deserializer)?
            .parse()
            .map_err(D::Error::custom)
    }
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Theme {
    #[default]
    Dark,
    Light,
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum TimeMode {
    #[default]
    Fixed,
    Follow,
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum CursorMode {
    #[default]
    None,
    Track,
    Measure,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum PanelMode {
    Time,
    Xy,
    Fft,
    Histogram,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum AxisStyle {
    Gutter,
    Inline,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum DashStyle {
    Solid,
    Dash,
    Dot,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum AnnotationDomain {
    Time,
    Frequency,
    Distribution,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct LinkedTime {
    pub t0: f64,
    pub t1: f64,
    pub linked: bool,
    pub paused: bool,
    #[serde(default)]
    #[serde(rename = "cursorT")]
    pub cursor_t: Option<f64>,
    pub mode: TimeMode,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct SeriesState {
    pub path: String,
    pub color_slot: u8,
    pub dash: DashStyle,
    pub width: f32,
    pub visible: bool,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct Annotation {
    pub id: String,
    pub series_path: String,
    pub domain: AnnotationDomain,
    pub anchor: f64,
    pub pinned_value: f64,
    pub label: String,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct EnsembleSeriesState {
    pub set_key: String,
    pub local_path: String,
    pub member_filter: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct PanelState {
    pub id: String,
    pub title: String,
    pub mode: PanelMode,
    pub axis_style: AxisStyle,
    #[serde(default)]
    pub x_signal: Option<String>,
    #[serde(default)]
    pub color_signal: Option<String>,
    pub color_by_time: bool,
    pub series: Vec<SeriesState>,
    #[serde(default)]
    pub ensemble: Option<EnsembleSeriesState>,
    #[serde(default)]
    pub y_range: Option<[f64; 2]>,
    #[serde(default)]
    pub x_range: Option<[f64; 2]>,
    #[serde(default)]
    pub x_label: Option<String>,
    #[serde(default)]
    pub y_label: Option<String>,
    #[serde(default)]
    pub c_label: Option<String>,
    #[serde(default)]
    pub time_window: Option<[f64; 2]>,
    pub annotations: Vec<Annotation>,
    pub show_stats: bool,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct LayoutCell {
    pub panel_id: String,
    pub width: f64,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct LayoutRow {
    pub height: f64,
    pub panels: Vec<LayoutCell>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct WorkspaceTab {
    pub id: String,
    pub title: String,
    pub cursor_mode: CursorMode,
    #[serde(default)]
    pub focused_panel_id: Option<String>,
    #[serde(default)]
    pub maximized_panel_id: Option<String>,
    pub panels: Vec<PanelState>,
    pub layout: Vec<LayoutRow>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct DerivedSignal {
    pub path: String,
    pub expr: String,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct SourceRecord {
    pub key: String,
    pub path: String,
    pub prefix: String,
    #[serde(default)]
    pub provider_id: Option<String>,
    #[serde(default)]
    pub decode_provenance: Option<String>,
    pub reconcile_legacy: bool,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum TimeUnitState {
    Seconds,
    Milliseconds,
    Microseconds,
    Nanoseconds,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum OriginKindState {
    Relative,
    AbsoluteEpoch,
    EventAligned,
    SyntheticIndex,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct TimeDomainState {
    pub unit: TimeUnitState,
    pub origin: OriginKindState,
    pub alignment_origin: f64,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct SetMemberState {
    pub source_key: String,
    pub missing: Vec<String>,
    pub scale: f64,
    pub offset: f64,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct SourceSetState {
    pub key: String,
    pub label: String,
    #[serde(with = "u64_string")]
    pub generation: u64,
    pub time_domain: TimeDomainState,
    pub members: Vec<SetMemberState>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct Session {
    pub app: String,
    pub schema_version: u32,
    pub theme: Theme,
    pub linked_time: LinkedTime,
    pub active_tab_id: String,
    pub tabs: Vec<WorkspaceTab>,
    pub favorites: Vec<String>,
    pub derived: Vec<DerivedSignal>,
    pub sources: Vec<SourceRecord>,
    pub source_sets: Vec<SourceSetState>,
}
