// @generated by protocol/scripts/generate-types.mjs. Do not edit.

use serde::{Deserialize, Serialize};

pub const SESSION_SCHEMA_VERSION: u32 = 31;

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Theme {
    #[default]
    Dark,
    Light,
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum TimeMode {
    #[default]
    Fixed,
    Follow,
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum CursorMode {
    #[default]
    None,
    Track,
    Measure,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum AxisStyle {
    Gutter,
    Inline,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum DashStyle {
    Solid,
    Dash,
    Dot,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum StatColumn {
    Min,
    Max,
    Mean,
    Rms,
    Cursor,
    N,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct LinkedTime {
    pub t0: f64,
    pub t1: f64,
    pub linked: bool,
    pub paused: bool,
    #[serde(default)]
    #[serde(rename = "cursorT")]
    pub cursor_t: Option<f64>,
    pub mode: TimeMode,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct SeriesRef {
    pub source_key: String,
    pub channel: String,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum SampleAxisSource {
    Time,
    Signal {
        #[serde(rename = "ref")]
        r#ref: SeriesRef,
    },
    Bundle {
        refs: Vec<SeriesRef>,
    },
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct ColorAxis {
    pub source: SampleAxisSource,
    #[serde(default)]
    pub range: Option<[f64; 2]>,
    #[serde(default)]
    pub label: Option<String>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum BindingKind {
    Query,
    Pick,
    Set,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct Binding {
    pub kind: BindingKind,
    #[serde(default)]
    pub selector: Option<String>,
    pub refs: Vec<SeriesRef>,
    #[serde(default)]
    pub set_id: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct SeriesOverride {
    #[serde(default)]
    pub target_ref: Option<SeriesRef>,
    #[serde(default)]
    pub target_selector: Option<String>,
    #[serde(default)]
    pub color_slot: Option<u8>,
    #[serde(default)]
    pub dash: Option<DashStyle>,
    #[serde(default)]
    pub width: Option<f32>,
    #[serde(default)]
    pub opacity: Option<f32>,
    #[serde(default)]
    pub visible: Option<bool>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum FocusKind {
    Series,
    Source,
    Channel,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct FocusEntry {
    pub kind: FocusKind,
    #[serde(default)]
    #[serde(rename = "ref")]
    pub r#ref: Option<SeriesRef>,
    #[serde(default)]
    pub source_key: Option<String>,
    #[serde(default)]
    pub channel: Option<String>,
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum GhostMode {
    Ghost,
    #[default]
    All,
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum StyleDimension {
    Focus,
    #[default]
    Source,
    Channel,
    Set,
    Attr,
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum LegendState {
    Badge,
    #[default]
    Keys,
    Roster,
    Rail,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum LegendAnchor {
    TopLeft,
    TopRight,
    BottomLeft,
    BottomRight,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum LegendDock {
    Left,
    Right,
    Top,
    Bottom,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum NamedSetKind {
    Query,
    Pick,
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum AnnotationDisplay {
    #[default]
    Labels,
    Markers,
    Hidden,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct NamedSet {
    pub id: String,
    pub name: String,
    pub kind: NamedSetKind,
    #[serde(default)]
    pub selector: Option<String>,
    pub refs: Vec<SeriesRef>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct Annotation {
    pub id: String,
    pub series_path: String,
    pub anchor: f64,
    #[serde(default)]
    pub pinned_x: Option<f64>,
    pub pinned_value: f64,
    pub label: String,
    pub offset: [f64; 2],
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct PanelState {
    pub id: String,
    pub title: String,
    pub axis_style: AxisStyle,
    pub bindings: Vec<Binding>,
    #[serde(default)]
    pub color_by: Option<StyleDimension>,
    #[serde(default)]
    pub dash_by: Option<StyleDimension>,
    #[serde(default)]
    pub width_by: Option<StyleDimension>,
    pub line_width: f32,
    pub ghost_opacity: f32,
    pub overrides: Vec<SeriesOverride>,
    pub focus: Vec<FocusEntry>,
    pub ghost_mode: GhostMode,
    pub legend_state: LegendState,
    #[serde(default)]
    pub legend_position: Option<[f64; 2]>,
    #[serde(default)]
    pub legend_size: Option<[f64; 2]>,
    #[serde(default)]
    pub legend_anchor: Option<LegendAnchor>,
    #[serde(default)]
    pub legend_dock: Option<LegendDock>,
    pub legend_hint_dismissed: bool,
    pub x_axis: SampleAxisSource,
    #[serde(default)]
    pub color_axis: Option<ColorAxis>,
    #[serde(default)]
    pub y_range: Option<[f64; 2]>,
    #[serde(default)]
    pub x_range: Option<[f64; 2]>,
    #[serde(default)]
    pub x_label: Option<String>,
    #[serde(default)]
    pub y_label: Option<String>,
    #[serde(default)]
    pub time_window: Option<[f64; 2]>,
    pub annotations: Vec<Annotation>,
    pub annotation_display: AnnotationDisplay,
    pub show_stats: bool,
    pub stat_columns: Vec<StatColumn>,
    #[serde(default)]
    pub stats_sort: Option<StatColumn>,
    pub stats_sort_descending: bool,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct LayoutCell {
    pub panel_id: String,
    pub width: f64,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct LayoutRow {
    pub height: f64,
    pub panels: Vec<LayoutCell>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct WorkspaceTab {
    pub id: String,
    pub title: String,
    pub cursor_mode: CursorMode,
    #[serde(default)]
    pub focused_panel_id: Option<String>,
    #[serde(default)]
    pub maximized_panel_id: Option<String>,
    pub panels: Vec<PanelState>,
    pub layout: Vec<LayoutRow>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct DerivedSignal {
    pub path: String,
    pub expr: String,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct DerivedBundleState {
    pub name: String,
    pub expr: String,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct SourceRecord {
    pub key: String,
    pub path: String,
    pub prefix: String,
    #[serde(default)]
    pub provider_id: Option<String>,
    #[serde(default)]
    pub decode_provenance: Option<String>,
    #[serde(default)]
    pub recipe_id: Option<String>,
    #[serde(default)]
    pub recipe_digest: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct Session {
    pub app: String,
    #[serde(default)]
    pub title: Option<String>,
    pub schema_version: u32,
    pub theme: Theme,
    pub linked_time: LinkedTime,
    pub active_tab_id: String,
    pub tabs: Vec<WorkspaceTab>,
    pub named_sets: Vec<NamedSet>,
    pub derived: Vec<DerivedSignal>,
    pub derived_bundles: Vec<DerivedBundleState>,
    pub sources: Vec<SourceRecord>,
}
