// @generated by protocol/scripts/generate-types.mjs. Do not edit.

use serde::{Deserialize, Serialize};

pub const PROTOCOL_VERSION: u32 = 1;

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct TimeWindow {
    pub t0: f64,
    pub t1: f64,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct TileRequest {
    pub protocol_version: u32,
    pub request_id: String,
    pub signal_ids: Vec<u64>,
    pub window: TimeWindow,
    pub pixel_width: u32,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct EnvelopeBin {
    pub t0: f64,
    pub t1: f64,
    #[serde(default)]
    pub first: Option<f64>,
    #[serde(default)]
    pub last: Option<f64>,
    #[serde(default)]
    pub min: Option<f64>,
    #[serde(default)]
    pub max: Option<f64>,
    pub sample_count: u64,
    pub has_gap: bool,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct SignalTile {
    pub signal_id: u64,
    pub signal_path: String,
    #[serde(default)]
    pub unit: Option<String>,
    pub level: u32,
    pub bins: Vec<EnvelopeBin>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct TileResponse {
    pub protocol_version: u32,
    pub request_id: String,
    pub series: Vec<SignalTile>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct SignalSummary {
    pub signal_id: u64,
    pub path: String,
    #[serde(default)]
    pub unit: Option<String>,
    pub point_count: u64,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct SourceSummary {
    pub source_id: u64,
    pub path: String,
    pub point_count: u64,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct IngestResponse {
    pub protocol_version: u32,
    pub source: SourceSummary,
    pub signals: Vec<SignalSummary>,
}
