// @generated by protocol/scripts/generate-types.mjs. Do not edit.

use serde::{Deserialize, Serialize};

pub const PROTOCOL_VERSION: u32 = 9;

mod u64_string {
    use serde::{Deserialize, Deserializer, Serializer, de::Error};

    #[allow(clippy::trivially_copy_pass_by_ref)]
    pub fn serialize<S>(value: &u64, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(&value.to_string())
    }

    pub fn deserialize<'de, D>(deserializer: D) -> Result<u64, D::Error>
    where
        D: Deserializer<'de>,
    {
        String::deserialize(deserializer)?
            .parse()
            .map_err(D::Error::custom)
    }
}

mod u64_vec_string {
    use serde::{Deserialize, Deserializer, Serialize, Serializer, de::Error};

    pub fn serialize<S>(values: &[u64], serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        values
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .serialize(serializer)
    }

    pub fn deserialize<'de, D>(deserializer: D) -> Result<Vec<u64>, D::Error>
    where
        D: Deserializer<'de>,
    {
        Vec::<String>::deserialize(deserializer)?
            .into_iter()
            .map(|value| value.parse().map_err(D::Error::custom))
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct TimeWindow {
    pub t0: f64,
    pub t1: f64,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct IngestBatchRequest {
    pub paths: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct BatchJob {
    #[serde(with = "u64_string")]
    pub job_id: u64,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum BatchState {
    Running,
    Done,
    Partial,
    Failed,
    Cancelled,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum FileState {
    Pending,
    Running,
    Done,
    Failed,
    Cancelled,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct BatchFailure {
    pub path: String,
    pub error: String,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct BatchStatus {
    pub state: BatchState,
    pub fraction: f64,
    #[serde(with = "u64_string")]
    pub total: u64,
    #[serde(with = "u64_string")]
    pub done: u64,
    #[serde(with = "u64_string")]
    pub failed: u64,
    pub recent_failures: Vec<BatchFailure>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct BatchDetailRequest {
    #[serde(with = "u64_string")]
    pub job_id: u64,
    pub offset: u32,
    pub limit: u32,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct BatchFileStatus {
    pub path: String,
    pub state: FileState,
    #[serde(default)]
    pub error: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct BatchDetail {
    pub entries: Vec<BatchFileStatus>,
    #[serde(with = "u64_string")]
    pub total: u64,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct FormatDescriptor {
    pub id: String,
    pub label: String,
    pub extensions: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct IngestRequest {
    pub path: String,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct TileRequest {
    pub request_id: String,
    #[serde(with = "u64_vec_string")]
    pub signal_ids: Vec<u64>,
    pub window: TimeWindow,
    pub pixel_width: u32,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct EnvelopeBin {
    pub t0: f64,
    pub t1: f64,
    #[serde(default)]
    pub first: Option<f64>,
    #[serde(default)]
    pub last: Option<f64>,
    #[serde(default)]
    pub min: Option<f64>,
    #[serde(default)]
    pub max: Option<f64>,
    pub sum: f64,
    pub sum_sq: f64,
    #[serde(with = "u64_string")]
    pub finite_count: u64,
    #[serde(with = "u64_string")]
    pub sample_count: u64,
    pub has_gap: bool,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct SignalTile {
    #[serde(with = "u64_string")]
    pub signal_id: u64,
    pub signal_path: String,
    #[serde(default)]
    pub unit: Option<String>,
    pub level: u32,
    pub bins: Vec<EnvelopeBin>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct TileResponse {
    pub request_id: String,
    pub series: Vec<SignalTile>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct SampleRequest {
    pub request_id: String,
    #[serde(with = "u64_vec_string")]
    pub signal_ids: Vec<u64>,
    pub window: TimeWindow,
    pub max_points: u32,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct SampleSeries {
    #[serde(with = "u64_string")]
    pub signal_id: u64,
    pub signal_path: String,
    #[serde(default)]
    pub unit: Option<String>,
    pub time: Vec<f64>,
    pub values: Vec<f64>,
    pub stride: u32,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct SampleResponse {
    pub request_id: String,
    pub series: Vec<SampleSeries>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct SignalSummary {
    #[serde(with = "u64_string")]
    pub signal_id: u64,
    #[serde(with = "u64_string")]
    pub source_id: u64,
    pub source_key: String,
    pub local_path: String,
    pub path: String,
    #[serde(default)]
    pub unit: Option<String>,
    #[serde(with = "u64_string")]
    pub point_count: u64,
    pub t_min: f64,
    pub t_max: f64,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct SourceSummary {
    #[serde(with = "u64_string")]
    pub source_id: u64,
    pub source_key: String,
    pub prefix: String,
    pub path: String,
    #[serde(with = "u64_string")]
    pub point_count: u64,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct IngestResponse {
    pub source: SourceSummary,
    pub signals: Vec<SignalSummary>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct IngestJob {
    #[serde(with = "u64_string")]
    pub job_id: u64,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum IngestStage {
    Decode,
    Pyramid,
    Cache,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum IngestState {
    Running,
    Done,
    Failed,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct IngestStatus {
    pub state: IngestState,
    pub stage: IngestStage,
    pub fraction: f64,
    #[serde(default)]
    pub response: Option<IngestResponse>,
    #[serde(default)]
    pub error: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct DerivedRequest {
    pub path: String,
    pub expr: String,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct RemoveSignalRequest {
    pub path: String,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum SessionDialogMode {
    Open,
    Save,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct PickSessionRequest {
    pub mode: SessionDialogMode,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct SaveSessionRequest {
    pub session_json: String,
    #[serde(default)]
    pub path: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct LoadSessionRequest {
    #[serde(default)]
    pub path: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct LoadedSession {
    pub session_json: String,
    #[serde(default)]
    pub path: Option<String>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum ExportRange {
    Visible,
    All,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum ExportFidelity {
    Preview,
    Standard,
    High,
    Full,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct ExportEstimateRequest {
    pub session_json: String,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct ExportEstimate {
    pub entries: Vec<ExportEstimateEntry>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct ExportEstimateEntry {
    pub range: ExportRange,
    pub fidelity: ExportFidelity,
    #[serde(with = "u64_string")]
    pub bytes: u64,
    #[serde(with = "u64_string")]
    pub series_total: u64,
    #[serde(with = "u64_string")]
    pub series_decimated: u64,
    #[serde(with = "u64_string")]
    pub series_full_rate: u64,
    #[serde(with = "u64_string")]
    pub coarsest_ratio: u64,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct ExportWriteRequest {
    pub session_json: String,
    pub range: ExportRange,
    pub fidelity: ExportFidelity,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum ExportFileKind {
    Png,
    Csv,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct SaveExportFileRequest {
    pub file_name: String,
    pub kind: ExportFileKind,
    pub data_base64: String,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct SaveExportFileToDirectoryRequest {
    pub directory: String,
    pub file_name: String,
    pub kind: ExportFileKind,
    pub data_base64: String,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct BakedSignal {
    pub summary: SignalSummary,
    pub levels: Vec<Vec<EnvelopeBin>>,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct SnapshotManifest {
    pub session_json: String,
    pub signals: Vec<BakedSignal>,
}
