// @generated by protocol/scripts/generate-types.mjs. Do not edit.

use serde::{Deserialize, Serialize};

pub const PREFERENCES_SCHEMA_VERSION: u32 = 1;

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum FontFamily {
    #[default]
    Inter,
    Dejavu,
    Arimo,
    Jetbrains,
}

#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]
pub struct Preferences {
    pub schema_version: u32,
    pub ui_font_family: FontFamily,
    pub plot_font_family: FontFamily,
    pub ui_font_size: f64,
    pub plot_font_size: f64,
}
