name: Code Coverage

on: push

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: tanged123
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Install frontend dependencies
        run: ./scripts/setup.sh

      - name: Run coverage
        run: ./scripts/coverage.sh

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/coverage/rust.lcov,./build/coverage/frontend/lcov.info
          version: v11.2.7
          fail_ci_if_error: true
